### PR TITLE
move models away from app.py

### PR DESCRIPTION
**Pull request by MaxPresman**
pr'ing the stashed change to allow more flexibility on the app.py

### CODE REVIEW

**Comment by tmaybe** [comment]
Nice, I was thinking of doing this myself. Will review.

**Comment by tmaybe** [comment]
Hey @MaxPresman, we've scheduled some time to review and merge this request next week, thank you.

**Comment by MaxPresman** [comment]
oki, i'll rebase.

**Comment by MaxPresman** [comment]
rebased

**Comment by tmaybe** [comment]
Thanks @MaxPresman! It's much more manageable with the models in their own file.

**Comment by MaxPresman** [comment]
yiss! it's very awesome

**Pull request merged**
