### PR TITLE
Add a `include_issues` flag for project requests

### PR DESCRIPTION
**Pull request by ondrae**
This PR was started by @cweems then I added tests.

Its great! It is so much faster now. I've put this branch up and staging and ran some [speed tests](https://www.runscope.com/radar/55dtxuu0l98j/735ad232-7a65-46f7-bb2c-a8a95a3956ab/history/2937e14b-6b32-4ac8-93a0-5506704e8276) on it. You can view the results at  Four times faster!

### CODE REVIEW

**Comment by cweems** [comment]
@ondrae Awesome! Thanks for picking this up. Not sure why Travis is failing though? Happy to talk more tomorrow.

**Comment by ondrae** [comment]
The failing tests are the fault of some included testing library. They pass fine on my machine, so there is some new bug in hosted version. I'm not worried about it.

The thing I am worried about, is that this PR changes existing attribute. If the issues aren't included, then the 'issues' attribute isnt there at all, which could break some users stuff. Whats a different way to handle it?

1. If we don't include issues, don't show the attribute. This may break something depending on that key existing.
2. Still include the `issues` attribute, but just leave it null. This may make people think that this project doesn't have issues, which is misleading. An actual project with no issues, instead has an empty list.
3. Include the `issues` attribute, but have a string saying "use include_issues to include issues". That may break thing too if anyone is depending on the issues attribute to be a list.

Any ideas?

**Comment by cweems** [comment]
@ondrae I think that the third option is the best approach. If someone is depending upon the issues attribute to be a list, chances are that not having the issues included for them will be a breaking change anyway. In this case I think that having a string pointing out the change would be useful.

Happy to look at this for a bit now.

**Comment by migurski** [comment]
Could the string instead be a valid URL with the `include_issues` flag turned on, or a link to the issues themselves? Then a machine could read it.

**Comment by cweems** [comment]
@migurski Yep that sounds like a better solution.

**Comment by cweems** [comment]
@ondrae Would you mind adding me to this repo? Looks like I don't have access since we removed my status as owner.

**Comment by cweems** [comment]
Will push after I'm added. Here's the format of the issues array when we're excluding issues that I came up with.

```python
issues:  [
            {
                "api_url": "http://codeforamerica.org/api/projects?include_issues=true",
                "body": "This is a placeholder. To include Github issues from projects in the API response, add include_issues=true as a parameter. Including issues significantly increases API response time.",
                "created_at": "",
                "html_url": "",
                "id": null,
                "labels": [],
                "project_id": null,
                "title": "CFAPI Did Not Return Github Issues",
                "updated_at": ""
            }
        ]
```

**Comment by ondrae** [comment]
Should be a collaborator now.

**Comment by ondrae** [comment]
ohh, I don't know. I see what you are doing by making it have the same format as an issue, but I feel that may be even more confusing and would then fail silently. 

How about instead its:
```
issues: "http://codeforamerica.org/api/projects/1/issues"
```

**Comment by ondrae** [comment]
In [my latest commit](https://github.com/codeforamerica/cfapi/commit/b7ce06e006153bdd11cc70c7907acfc4aee221b9) I made every project return a link to its issues. If the include_issues flag is in the url, then that link is replaced by a list of issues.

To do this, I added a new route where its now easy to get a projects issues.

**Comment by cweems** [comment]
@ondrae that looks like a better approach to me and seems to be working as expected. Think we're ready to merge?

**Comment by ondrae** [comment]
I've got it up on http://cfapi-staging.herokuapp.com/api/projects and http://cfapi-staging.herokuapp.com/api/projects?include_issues=true

Looks good to me. I'm going to merge.

**Comment by ondrae** [comment]
Five times faster!
screen shot 2016-02-01 at 3 37 03 pm

**Comment by migurski** [comment]
Whooosh!

**Pull request merged**
