### PR TITLE
Added org id with assumption it's same as name of an org but with das…

### PR DESCRIPTION
**Pull request by ralren**
Created an id column where I assume that the id resembles the name of an organization just with dashes in place of spaces. Ran tests and everything seems fine. Do let me know if I missed something.

### CODE REVIEW

**Comment by migurski** [comment]
Thank you @ralren, but it’s not a safe assumption to make. This relationship is currently true for all orgs, but not enforced anyplace and may/should be at some point replaced with an opaque ID which won’t be sensitive to organizations changing their names as they might.

**Comment by ralren** [comment]
I understand. What safe assumptions should I make in that case?

**Comment by migurski** [comment]
Can you say a little more about what you’re hoping to do?

**Comment by ralren** [comment]
I would like to add the organization id, but where will it be coming from? Should I assume that it will be a field added to the Brigade spreadsheet or grab it from another field?

**Comment by ondrae** [comment]
Hi @ralren thanks for this pull request. This is just what we were looking for in #209.

I've [cleaned it up](https://github.com/codeforamerica/cfapi/blob/add-id-%23209/app.py#L147) a little by using the functions we use elsewhere for cleaning the organization name first. 

I've also added the needed [migrations](https://github.com/codeforamerica/cfapi/blob/add-id-%23209/migrations/versions/532c3f11a51b_add_org_id_column.py) and a [little check](https://github.com/codeforamerica/cfapi/blob/add-id-%23209/run_update.py#L789) to update the orgs id.

I've had this code running on the [staging server](https://cfapi-staging.herokuapp.com/api/organizations) for most of the day and it looks all clear. I'll merge and push it to production when I get a chance. 

@migurski was right though that the way we use the name and the id is a little fragile and something we'll need to revisit.

Thanks again though for the pull request and your help.

**Comment by migurski** [comment]
Thank you for the followup, @ondrae!

**Comment by ralren** [comment]
Oh, wow, thanks @ondrae!

**Pull request merged**
