### PR TITLE
Add issue created_at and updated_at fields. resolves #218

### LINKED ISSUE #218: Add "created_at" and "updated_at" to Issues
#### Description
We should add these two time stamps to Issues. Doing so will:
* Allow a user to change how issues are returned using a sort_by parameter. #167 #216 
* Sorting by "created_at" is more stable than returning by id
* Sorting by "updated_at" lets us just find the most active issues.
* Make it easier for @sbenthall to start his civic issues analysis.

#### Files
app.py, run_update.py

#### Tasks
- [ ] Add "created_at" and "updated_at" to [Issue](https://github.com/codeforamerica/cfapi/blob/master/app.py#L394)
- [ ] Pull in theses values during run_update's [get_issues](https://github.com/codeforamerica/cfapi/blob/master/run_update.py#L580)
- [ ] Adjust some run_update_tests to make sure the time stamps are included.

### PR DESCRIPTION
**Pull request by smalley**

### CODE REVIEW

**Comment by tmaybe** [comment]
Hey @smalley, thank you, this looks super useful. We'll review it and put it up on staging next week.

**Comment by smalley** [comment]
@tmaybe Thanks for the opportunity to contribute. Definitely happy to patch up anything that shakes out in the review or rebase if you guys decide to merge #264 first. 

By the way, do you guys generally prefer that commits be squashed before being submitted as pull requests (a couple of those commits I have there are pretty small).

**Comment by tmaybe** [comment]
Thanks @smalley – I'll let you know if we need a rebase. And nah no need to squash your commits.

**Comment by tmaybe** [comment]
Hi @smalley, we just merged #264 and yes, we need a rebase for this PR, if you don't mind. If you have problems I can help.

**Comment by smalley** [comment]
@tmaybe okay I think I've got this rebased on top of the current head. I'm a little iffy on the db migration script post merge though.

**Comment by tmaybe** [comment]
Thanks @smalley, reviewing it now.

**Comment by tmaybe** [comment]
Merged! @smalley, thanks for your help!

**Pull request merged**
