### PR TITLE
Save None values to db instead of empty strings

### LINKED ISSUE #223: Both status and tags are being saved as empty strings instead of null
When a Brigade uses a csv or spreadsheet to describe their projects, the `status` column and the `tags` column are being saved as empty strings instead of null.

 See [this project](http://codeforamerica.org/api/projects/1252) for example.

### PR DESCRIPTION
**Pull request by tmaybe**
Closes #223

### CODE REVIEW

**Comment by tmaybe** [comment]
@ondrae could you take a look at this?

**Comment by tmaybe** [comment]
this is up on staging

**Comment by ondrae** [comment]
Good work. I'm pushing it to production now.

**Comment by ondrae** [comment]
Looks good on production

**Pull request merged**
