### PR TITLE
Optimized Imports

### PR DESCRIPTION
**Pull request by PatrickEGorman**
Fresh coder looking to get involved in bigger things.  Didn't change much except for removing and reorganizing some imports

### CODE REVIEW

**Comment by tmaybe** [comment]
Thanks @PatrickEGorman will take a look this week!

**Comment by PatrickEGorman** [comment]
Honestly I'm not sure if what I did helped that much.  I'm just getting started and I'm not really that experienced contributing yet

**Comment by ondrae** [comment]
@PatrickEGorman Hey we're still working on some big bugs. We'll merge in your optimized imports as soon as we get our confidence back in the bugs we're battling.

**Comment by tmaybe** [comment]
pull request merged @PatrickEGorman, thank you! :100:

**Pull request closed without merging**
